services:
  - mysql
  - postgres

before_script:
  - apt-get install -y libpq-dev postgresql-client-9.4 libsqlite3-dev
  - docker-php-ext-install pgsql pdo pdo_pgsql pdo_sqlite
  - composer install --prefer-dist --no-interaction
  - psql -c 'create database yii2_queue_test;' -U postgres -h postgres
  - php tests/yii mysql-migrate --interactive=0
  - php tests/yii pgsql-migrate --interactive=0
  - php tests/yii sqlite-migrate --interactive=0

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: mysql_database
  MYSQL_ROOT_PASSWORD: mysql_strong_password

test:5.6:
  image: mikk150/yii2-base:5.6
  script:
    - vendor/bin/phpunit

test:7.0:
  image: mikk150/yii2-base:7.0
  script:
    - vendor/bin/phpunit

test:7.1:
  image: mikk150/yii2-base:7.1
  script:
    - vendor/bin/phpunit